Create User interface for TicTacToe
SamroodAli/tic-tac-toe pull request #9
Opened 2021-03-25 14:17 UTC by marijanbrvar

- We created a branch for the user interface
- We added the game board 3x3 grid and output on the screen
- Assign values to each grid item

2021-03-25 16:54 UTC, DeliceLydia requested changes
# Status: Change Requested ![image](https://user-images.githubusercontent.com/44745855/112510496-25960200-8d9a-11eb-9a9f-fc5a5009d63d.png)

Amazing job so far guys👏👏👏 
- User interface looks amazing
- README is professional
- PR is descriptive

There is a small change you need to make to be ready to move on
- Validate your user input so that it can not accept empty input and submit
for another code review

# Keep working hard ![image](https://user-images.githubusercontent.com/44745855/112511654-4ad74000-8d9b-11eb-961f-7a4b97fb66bd.png)

All the best,

Lydia Ingabire

2021-03-26 08:20 UTC, SamroodAli commented
We had created an issue #13 for user input validation and successfully implemented and tested a valid user input check.

2021-03-26 09:20 UTC, pacyL2K19 reviewed
# Status: Changes required :stop_sign: 
Hello @marijanbrvar, you made a great job so far, I enjoyed playing your game, reading your code and you almost fit all the requirements for this milestone, just a small update before moving forward still needed:
- [ ] The game only plays 8 times instead of 9, please check it and test before submitting again (See the screenshot) below
![errorUserint](https://user-images.githubusercontent.com/61581306/112609906-66365f80-8e1c-11eb-85cc-92d6ebacd8a5.png)
- [ ] Even optional; kindly try to work on the comment below :arrow_down:
> 
In case you need anything else from me, don't hesitate to reach out on slack totally available 
### Happy coding :desktop_computer:

2021-03-26 10:01 UTC, marijanbrvar commented on bin/main.rb
>  4.times do
Thank you for your comment. Currently, we are at Mileston 2, and we did understand that game logic is for the next milestone. The only thing that we did in this Milestone is the simple user interface. However, if you insist, we can change that as well!. Thank you for your time and effort.

Sam & Marian

2021-03-26 10:51 UTC, SamroodAli commented on bin/main.rb
>  4.times do
Thank you for the review. We have used a `while` loop instead of the `times` loop. The `while` loop uses a boolean variable `game_over` to check whether the game is over based on the occupancy of the board. We will work on the game logic for the next milestone. Thank you for your time and consideration.

2021-03-26 11:18 UTC, pacyL2K19 commented on bin/main.rb
>  4.times do
It's always a pleasure, keep going ahead

2021-03-26 16:55 UTC, elisha2kyakpo1 approved these changes
[OPTIONAL] Work on validations for game inputs, it's a requirement especially in the next milestone. For now, lets celebraty✔👍🙌👏🎁😆👍😎

2021-03-26 16:55 UTC, elisha2kyakpo1 commented on bin/main.rb
> +  while move.empty?
You are only validating for the empty board. I would like you guys to validate for a string(your board accepts a string character.

2021-03-27 02:19 UTC, SamroodAli commented on bin/main.rb
> +  while move.empty?
Hey there, thank you so much for the review. Yes, we will definitely validate the user input to check for Strings. Thanks for the valuable feedback. Happy coding! @elisha2kyakpo1

2021-03-27 02:19 UTC, merged